export * from "./generated/api";
export * from "./generated/api.schemas";
export { setBaseUrl, setAuthTokenGetter, ApiError, customFetch } from "./custom-fetch";
export type { AuthTokenGetter } from "./custom-fetch";
export * from "./checker";
export * from "./admin";
export * from "./auth-otp";
export * from "./auth-account";
export * from "./university-admin";
export * from "./invites";
export * from "./mentors";
export * from "./opportunities";
